{
 "title": "OpenIO Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Score",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggr:netdata_openio_score:avg_per_service",
     "legendFormat": "{{dim2}}"
    }
   ]
  },
  {
   "title": "Score distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_container_bytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 largest accounts (size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, netdata_openio_account_bytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 accounts with most containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(netdata_openio_container_count__average) by (dimension))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_container_objects__average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 largest accounts (object count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, netdata_openio_account_objects__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_container_count__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"received\"}) - sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"sent\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth per service from logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype",
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"received\"}) by (chart2) - sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"sent\"}) by (chart2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}}",
     "measurement": "openio_log_bandwidth",
     "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"openio_log_bandwidth\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /bytes_sent|sent/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bytes_sent" }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aggr:netdata_web_log_response_time_ms:sum{dimension=\"avg\", chart2=~\".*.oioswift\", instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "sum(aggr:netdata_web_log_response_time_ms:sum{instance=~\"[[host]]\"}) by (chart2, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}} {{dimension}}",
     "measurement": "openio_log_response_time",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_log_response_time\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\", \"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_response_codes:sum{dimension=~\"4xx|5xx\", instance=~\"[[host]]\"}) by (dimension, chart2)",
     "legendFormat": "{{chart2}} {{dimension}}"
    }
   ]
  },
  {
   "title": "Responses Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "sum(aggr:netdata_web_log_response_codes:sum{instance=~\"[[host]]\"}) by (dimension, chart2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}} {{dimension}}",
     "measurement": "openio_log_response_codes",
     "query": "SELECT sum(value) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"[[host]]\"}) by (chart2, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}} {{dimension}}",
     "measurement": "openio_log_http_method",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_log_http_method\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Keys",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(netdata_redis_keys_keys_average{instance=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(netdata_redis_keys_keys_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).keys\")) by (chart2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(netdata_redis_operations_operations_persec_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).operations\")) by (chart2)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{chart2}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 58 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_redis_hit_rate_percent_average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(netdata_redis_memory_kilobytes_average{dimension=\"total\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).memory\")) by (chart2)",
     "legendFormat": "{{chart2}}"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 58 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(netdata_redis_net_kilobits_persec_average{instance=~\"[[host]]\", dimension=\"in\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).net\")) by (chart2)\n- sum(label_replace(netdata_redis_net_kilobits_persec_average{instance=~\"[[host]]\", dimension=\"out\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).net\")) by (chart2)\n",
     "legendFormat": "{{chart2}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Event queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_tube: $tag_type",
     "expr": "sum(netdata_beanstalk_jobs_jobs_average{instance=~\"[[host]]\"}) by (family, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "tube" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ dimension }} {{ family }}",
     "measurement": "openio_beanstalkd_tubes",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /^current.*/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"tube\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^current.*/" }
     ]
    }
   ]
  },
  {
   "title": "Events Processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_host: processed",
     "expr": "sum(netdata_beanstalk_jobs_rate_jobs_persec_average{dimension=\"total\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "tube" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "events",
     "measurement": "openio_beanstalkd_tubes",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" = 'total_jobs' AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"type\", \"tube\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "total_jobs" }
     ]
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Datasize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: approximate_data_size",
     "expr": "sum(netdata_openio_zk_approximate_data_size__average{chart=\"openio.zk_approximate_data_size\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "data_size",
     "measurement": "openio_zookeeper_zk_approximate_data_size",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_approximate_data_size\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Pending Syncs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: pending_syncs",
     "expr": "sum(netdata_openio_zk_pending_syncs__average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openio_zookeeper_zk_pending_syncs",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_pending_syncs\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: avg_latency",
     "expr": "avg(netdata_openio_zk_max_latency__average{chart=\"openio.zk_max_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "measurement": "openio_zookeeper_zk_avg_latency",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_namespace: max_latency",
     "expr": "avg(netdata_openio_zk_avg_latency__average{chart=\"openio.zk_avg_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "average",
     "measurement": "openio_zookeeper_zk_max_latency",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: requests",
     "expr": "avg(netdata_openio_zk_outstanding_requests__average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "outstanding_requests",
     "measurement": "openio_zookeeper_zk_outstanding_requests",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_outstanding_requests\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}