{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 2, "y": 0 }, "content": "## System" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 16, "y": 0 }, "content": "## Network" },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",dimension=\"user\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"value\") * -1 + 100 FROM \"[[DS]]\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"mode\" = 'idle' AND \"cpu\" = 'system' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "system" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 2 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",dimension=\"used\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ram\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 2 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Percent used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"}) / (sum(netdata_disk_space_GB_average{instance=~\"[[host]]\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}) - sum(netdata_net_net_kilobits_persec_average{dimension=\"sent\", instance=~\"[[host]]\"})\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  },
  {
   "title": "SDS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 2 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"received\"}) - sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"sent\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 2, "y": 6 }, "content": "## OpenIO" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 16, "y": 6 }, "content": "## Dashboards" },
  {
   "title": "Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(aggr:netdata_web_log_response_time_ms:sum{chart2=~\".*.oioswift\", instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_beanstalk_jobs_jobs_average{instance=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "Events/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_beanstalk_jobs_rate_jobs_persec_average{dimension=\"total\",instance=~\"[[host]]\"})"
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 6, "x": 16, "y": 8 } },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 2, "y": 12 }, "content": "## Data" },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_container_count__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_objects__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stored data",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_bytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}