{
 "title": "Host details",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",instance=~\"[[host]]\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"$host\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(netdata_system_load_load_average{chart=\"system.load\",family=\"load\",instance=~\"$host\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "N/A",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decmbytes" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bandwidth (bps)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$host\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Network Bandwidth (Bps)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$host\"}) by (dimension) /8",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks read IOps",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_ops_operations_persec_average{dimension=\"reads\", instance=~\"$host\"}",
       "legendFormat": "{{ family  }}"
      }
     ]
    },
    {
     "title": "Disks write IOps",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "-netdata_disk_ops_operations_persec_average{dimension=\"writes\", instance=~\"$host\"}",
       "legendFormat": "{{ family  }}"
      }
     ]
    },
    {
     "title": "Disks read bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_io_kilobytes_persec_average{dimension=\"reads\", instance=~\"$host\"}",
       "legendFormat": "{{ family  }}"
      }
     ]
    },
    {
     "title": "Disks write bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "-netdata_disk_io_kilobytes_persec_average{dimension=\"writes\", instance=~\"$host\"}",
       "legendFormat": "{{ family  }}"
      }
     ]
    },
    {
     "title": "Disk backlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"$host\"}",
       "legendFormat": "{{ family }}"
      }
     ]
    },
    {
     "title": "Disk utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"$host\"}",
       "legendFormat": "{{ family }}"
      }
     ]
    }
   ]
  },
  { "title": "OpenIO System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU usage by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"$host$\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disks reads usage by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_preads_kilobytes_persec_average{chart=\"apps.preads\",family=\"disk\",instance=~\"$host\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(netdata_openio_score__average{chart=\"openio.score\",family=\"Score\",instance=~\"$host\"}, \"dim2\", \"$1\", \"dimension\", \"(.*?)[_].*\")) by (dim2)",
     "legendFormat": "{{dim2}}"
    }
   ]
  },
  {
   "title": "Disks writes usage by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_pwrites_kilobytes_persec_average{chart=\"apps.pwrites\",family=\"disk\",instance=~\"$host\"}) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "OpenIO Services Req/s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\"}) by (chart2)",
       "legendFormat": "{{chart2}}"
      }
     ]
    },
    {
     "title": "Swift req/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.oioswift\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "META1 req/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta1\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "RAWX req/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.rawx\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "META2 req/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta2\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Swift Response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_web_log_response_time_ms:sum{instance=~\"$host\", chart2=~\".*.oioswift\"}",
       "legendFormat": "{{ dimension }}"
      }
     ]
    },
    {
     "title": "RAWX Response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_web_log_response_time_ms:sum{instance=~\"$host\", chart2=~\".*.rawx\"}",
       "legendFormat": "{{ dimension }}"
      }
     ]
    }
   ]
  }
 ]
}