{
 "title": "Hosts comparison",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "y": 0, "w": 24, "h": 1, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU idle",
     "type": "graph",
     "gridPos": { "y": 1, "w": 12, "h": 9, "x": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",instance=~\"[[host]]\",dimension=\"idle\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM free",
     "type": "graph",
     "gridPos": { "y": 1, "w": 12, "h": 9, "x": 12 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"$host\",dimension=\"free\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Average (avg)",
     "type": "graph",
     "gridPos": { "y": 10, "w": 12, "h": 9, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(netdata_system_load_load_average{chart=\"system.load\",family=\"load\",instance=~\"$host\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM cached",
     "type": "graph",
     "gridPos": { "y": 10, "w": 12, "h": 9, "x": 12 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"$host\",dimension=\"cached\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "y": 1, "w": 24, "h": 1, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bandwidth (bps)",
     "type": "graph",
     "gridPos": { "y": 2, "w": 12, "h": 9, "x": 0 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$host\"}) by (dimension,instance)",
       "legendFormat": "{{instance}}-{{dimension}}"
      }
     ]
    },
    {
     "title": "Network Bandwidth (Bps)",
     "type": "graph",
     "gridPos": { "y": 2, "w": 12, "h": 9, "x": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$host\"}) by (dimension,instance) /8",
       "legendFormat": "{{instance}}-{{dimension}}"
      }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "y": 2, "w": 24, "h": 1, "x": 0 } },
  {
   "title": "Disks read IOps",
   "type": "graph",
   "gridPos": { "y": 3, "w": 12, "h": 9, "x": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_ops_operations_persec_average{dimension=\"reads\", instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "Disks write IOps",
   "type": "graph",
   "gridPos": { "y": 3, "w": 12, "h": 9, "x": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "-sum(netdata_disk_ops_operations_persec_average{dimension=\"writes\", instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "Disks read bandwidth",
   "type": "graph",
   "gridPos": { "y": 12, "w": 12, "h": 9, "x": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{dimension=\"reads\", instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "Disks write bandwidth",
   "type": "graph",
   "gridPos": { "y": 12, "w": 12, "h": 9, "x": 12 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "-sum(netdata_disk_io_kilobytes_persec_average{dimension=\"writes\", instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "Disk backlog avg",
   "type": "graph",
   "gridPos": { "y": 21, "w": 24, "h": 7, "x": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk utilization avg",
   "type": "graph",
   "gridPos": { "y": 28, "w": 24, "h": 7, "x": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "  avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "OpenIO System",
   "type": "row",
   "gridPos": { "y": 35, "w": 24, "h": 1, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by service",
     "type": "graph",
     "gridPos": { "y": 4, "w": 12, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"$host$\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Disks reads usage by service",
     "type": "graph",
     "gridPos": { "y": 4, "w": 12, "h": 8, "x": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_preads_kilobytes_persec_average{chart=\"apps.preads\",family=\"disk\",instance=~\"$host\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Scores",
     "type": "graph",
     "gridPos": { "y": 12, "w": 12, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(label_replace(netdata_openio_score__average{chart=\"openio.score\",family=\"Score\",instance=~\"$host\"}, \"dim2\", \"$1\", \"dimension\", \"(.*?)[_].*\")) by (dim2)",
       "legendFormat": "{{dim2}}"
      }
     ]
    },
    {
     "title": "Disks writes usage by service",
     "type": "graph",
     "gridPos": { "y": 12, "w": 12, "h": 8, "x": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_pwrites_kilobytes_persec_average{chart=\"apps.pwrites\",family=\"disk\",instance=~\"$host\"}) by (dimension)",
       "legendFormat": "{{ dimension }}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenIO Services Req/s",
   "type": "row",
   "gridPos": { "y": 36, "w": 24, "h": 1, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / s",
     "type": "graph",
     "gridPos": { "y": 5, "w": 24, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\"}) by (chart2)",
       "legendFormat": "{{chart2}}"
      }
     ]
    },
    {
     "title": "Swift req/s",
     "type": "graph",
     "gridPos": { "y": 13, "w": 12, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.oioswift\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "META1 req/s",
     "type": "graph",
     "gridPos": { "y": 13, "w": 12, "h": 8, "x": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta1\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "RAWX req/s",
     "type": "graph",
     "gridPos": { "y": 21, "w": 12, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.rawx\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "META2 req/s",
     "type": "graph",
     "gridPos": { "y": 21, "w": 12, "h": 8, "x": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta2\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Swift Response time",
     "type": "graph",
     "gridPos": { "y": 29, "w": 12, "h": 8, "x": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_web_log_response_time_ms:sum{instance=~\"$host\", chart2=~\".*.oioswift\"}",
       "legendFormat": "{{ dimension }}"
      }
     ]
    },
    {
     "title": "RAWX Response time",
     "type": "graph",
     "gridPos": { "y": 29, "w": 12, "h": 8, "x": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_web_log_response_time_ms:sum{instance=~\"$host\", chart2=~\".*.rawx\"}",
       "legendFormat": "{{ dimension }}"
      }
     ]
    }
   ]
  }
 ]
}