{
 "title": "Filesystem connector",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   },
   {
    "name": "instance",
    "query": "label_values(netdata_oiofs_cache_latency_us_average{instance=~\"[[host]]\"}, family)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * ((sum(probe_success{service=\"oiofs\"} == 1) or vector(0)) / (count(probe_success{service=\"oiofs\"}) or vector(1)))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(probe_success{service=\"oiofs\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 }, "content": "### Cache" },
  {
   "title": "Cache ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_ops_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{dimension}} - {{family}} "
    }
   ]
  },
  {
   "title": "Cache chunks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_chunks_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Cache latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_latency_us_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Cache age",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_age_us_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_size_bytes_average{instance=~\"[[host]]\", dimension!~\"read\", family=\"[[instance]]\"}",
     "legendFormat": "{{dimension}} - {{family}} "
    }
   ]
  },
  {
   "title": "Cache read rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_cache_size_bytes_average{instance=~\"[[host]]\", dimension=\"read\", family=\"[[instance]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 }, "content": "### Data" },
  {
   "title": "SDS data rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_sds_bytes_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{dimension}} - {{family}} "
    }
   ]
  },
  {
   "title": "Fuse I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_fuse_bytes_average{instance=~\"[[host]]\", family=\"[[instance]]\"}",
     "legendFormat": "{{dimension}} - {{family}} "
    }
   ]
  },
  {
   "title": "SDS ops total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_oiofs_sds_dl_ops_average{instance=~\"[[host]]\", family=~\"[[instance]]\"}) by (instance, family)",
     "legendFormat": "download - {{family}} "
    },
    {
     "expr": "sum(netdata_oiofs_sds_ul_ops_average{instance=~\"[[host]]\", family=~\"[[instance]]\"}) by (instance, family)",
     "legendFormat": "upload - {{family}} "
    }
   ]
  },
  {
   "title": "SDS errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "netdata_oiofs_sds_dl_ops_average{instance=~\"[[host]]\", dimension=\"failed\", family=\"[[instance]]\"}",
     "legendFormat": "download - {{family}}"
    },
    {
     "expr": "netdata_oiofs_sds_ul_ops_average{instance=~\"[[host]]\", dimension=\"failed\", family=\"[[instance]]\"}",
     "legendFormat": "upload - {{family}}"
    }
   ]
  }
 ]
}