{
 "title": "Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(probe_success, host)"
   },
   {
    "name": "service",
    "query": "label_values(probe_success, service)"
   },
   {
    "name": "tcpcheck_service",
    "query": "label_values(probe_success{job=\"tcpcheck\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * count(probe_success == 1) / count(probe_success)"
    }
   ]
  },
  {
   "title": "Passed checks",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(probe_success == 1)" }
   ]
  },
  {
   "title": "Failed checks",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ALERTS) OR vector(0)" }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "repeat": "service",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "[[service]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"} == 1) OR vector(0)) / count(probe_success{service=\"[[service]]\", host=~\"[[host]]\"})"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Failed checks",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "probe_success == 0" }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}