{
 "title": "Network",
 "description": "Network information",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Network" },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_net_packets_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "net_packets",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_net_drops_drops_persec_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "net_drops",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net_drops\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_errors_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_errors",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "content": "# IPv4 Networking" },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",family=\"packets\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_packets",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_packets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_errors_packets_persec_average{chart=\"ipv4.errors\",family=\"errors\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_errors",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "established",
     "expr": "sum(netdata_ipv4_tcpsock_active_connections_average{chart=\"ipv4.tcpsock\",family=\"tcp\",dimension=\"connections\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "established",
     "measurement": "ipv4_tcpsock",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcpsock\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Handshakes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_tcphandshake_events_persec_average{chart=\"ipv4.tcphandshake\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_tcphandshake",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcphandshake\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_tcperrors_packets_persec_average{chart=\"ipv4.tcperrors\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_tcperrors",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcperrors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_ipv4_udppackets_packets_persec_average{chart=\"ipv4.udppackets\",family=\"udp\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ipv4_udppackets",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_udppackets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}