{
 "title": "OpenIO System",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype: $tag_mode",
     "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_cpu\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "cpu" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype: $tag_type",
     "expr": "sum(netdata_apps_preads_kilobytes_persec_average{chart=\"apps.preads\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "reads - {{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_preads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "disk" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" }
     ]
    },
    {
     "alias": "$tag_servicetype: $tag_type",
     "expr": "sum(netdata_apps_pwrites_kilobytes_persec_average{chart=\"apps.pwrites\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "writes - {{dimension}}",
     "measurement": "openio",
     "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"apps_pwrites\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "disk" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" }
     ]
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype",
     "expr": "sum(netdata_apps_files_open_files_average{chart=\"apps.files\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_files\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "files" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype",
     "expr": "sum(netdata_apps_mem_MB_average{chart=\"apps.mem\",family=\"mem\",instance=~\"[[host]]\"}) by (dimension)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_mem\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "mem" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype",
     "expr": "sum(netdata_apps_processes_processes_average{chart=\"apps.processes\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_processes\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "processes" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype",
     "expr": "sum(netdata_apps_threads_threads_average{chart=\"apps.threads\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_threads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "threads" }
     ]
    }
   ]
  },
  {
   "title": "Opened Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_servicetype",
     "expr": "sum(netdata_apps_sockets_open_sockets_average{chart=\"apps.sockets\",family=\"net\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_sockets\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "sockets" }
     ]
    }
   ]
  }
 ]
}