{
 "title": "OpenIO",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",dimension=\"user\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"value\") * -1 + 100 FROM \"[[DS]]\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"mode\" = 'idle' AND \"cpu\" = 'system' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "mode", "operator": "=", "value": "idle" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "system" }
       ]
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "format": "decmbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",dimension=\"used\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ram",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ram\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
       ]
      }
     ]
    },
    {
     "title": "DiskSpace Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk_space",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
       ]
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "format": "Kbits",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}) + sum(netdata_net_net_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"})\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_mode",
       "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "mode" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "cpu",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"cpu\" WHERE (\"cpu\" = 'system') AND $timeFilter GROUP BY time([[ds_int]]), \"mode\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "system" }
       ]
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ram",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_avg",
       "expr": "avg(netdata_system_load_load_average{chart=\"system.load\",family=\"load\",instance=~\"[[host]]\"}) by (dimension)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "avg" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension }}",
       "measurement": "load",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"load\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"avg\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "context_switches",
       "expr": "sum(netdata_system_ctxt_context_switches_persec_average{chart=\"system.ctxt\",family=\"processes\",dimension=\"switches\",instance=~\"[[host]]\"})\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "context switches",
       "measurement": "ctxt_switches",
       "query": "SELECT sum(\"value\")  FROM \"[[DS]]\".\"ctxt_switches\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_system_processes_processes_average{chart=\"system.processes\",family=\"processes\",dimension=\"running\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "running",
       "measurement": "processes",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"processes\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Commited Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "commited_memory",
       "expr": "sum(netdata_mem_committed_MB_average{chart=\"mem.committed\",family=\"system\",dimension=\"Committed_AS\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed memory",
       "measurement": "mem_committed",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"mem_committed\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "alias": "$tag_operation",
       "expr": "sum(netdata_system_io_kilobytes_persec_average{chart=\"system.io\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "io",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"io\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"operation\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_operation",
       "expr": "sum(netdata_disk_ops_operations_persec_average{chart=\"disk_ops.vda\",family=\"vda\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_ops",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_disk_space_GB_average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_space",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Files Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_disk_inodes_Inodes_average{instance=~\"[[host]]\"}) by (dimension)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_inodes",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_inodes\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Backlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "maximum",
       "expr": "quantile(0.95, avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"}))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "95th percentile",
       "measurement": "disk_backlog",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_backlog\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "expr": "avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"})",
       "legendFormat": "maximum"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "maximum",
       "expr": "avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "maximum",
       "measurement": "disk_util",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_util\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "expr": "quantile(0.95, avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"}))",
       "legendFormat": "95th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_net_packets_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net_packets",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_net_drops_drops_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net_drops",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net_drops\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_errors_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_errors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",family=\"packets\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_packets",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_packets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)\n\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_errors_packets_persec_average{chart=\"ipv4.errors\",family=\"errors\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_errors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "established",
       "expr": "sum(netdata_ipv4_tcpsock_active_connections_average{chart=\"ipv4.tcpsock\",family=\"tcp\",dimension=\"connections\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "established",
       "measurement": "ipv4_tcpsock",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcpsock\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP Handshakes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_tcphandshake_events_persec_average{chart=\"ipv4.tcphandshake\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_tcphandshake",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcphandshake\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_tcperrors_packets_persec_average{chart=\"ipv4.tcperrors\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_tcperrors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcperrors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UDP Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_type",
       "expr": "sum(netdata_ipv4_udppackets_packets_persec_average{chart=\"ipv4.udppackets\",family=\"udp\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_udppackets",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_udppackets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenIO System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype: $tag_mode",
       "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "mode" ], "type": "tag" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_cpu\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "cpu" },
        { "condition": "AND", "key": "mode", "operator": "=", "value": "used" }
       ]
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype: $tag_type",
       "expr": "sum(netdata_apps_preads_kilobytes_persec_average{chart=\"apps.preads\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "reads - {{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_preads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "disk" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "read" }
       ]
      },
      {
       "alias": "$tag_servicetype: $tag_type",
       "expr": "sum(netdata_apps_pwrites_kilobytes_persec_average{chart=\"apps.pwrites\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "writes - {{dimension}}",
       "measurement": "openio",
       "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"apps_pwrites\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "disk" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "write" }
       ]
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype",
       "expr": "sum(netdata_apps_files_open_files_average{chart=\"apps.files\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_files\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "files" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype",
       "expr": "sum(netdata_apps_mem_MB_average{chart=\"apps.mem\",family=\"mem\",instance=~\"[[host]]\"}) by (dimension)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_mem\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "mem" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype",
       "expr": "sum(netdata_apps_processes_processes_average{chart=\"apps.processes\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_processes\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "processes" }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype",
       "expr": "sum(netdata_apps_threads_threads_average{chart=\"apps.threads\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_threads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "threads" }
       ]
      }
     ]
    },
    {
     "title": "Opened Sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_servicetype",
       "expr": "sum(netdata_apps_sockets_open_sockets_average{chart=\"apps.sockets\",family=\"net\",instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_sockets\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "resource", "operator": "=", "value": "sockets" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenIO Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "content": "# Score" },
    {
     "title": "Score",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Score",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_openio_score:avg_per_service",
       "legendFormat": "{{dim2}}"
      }
     ]
    },
    {
     "title": "Score distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "content": "# Storage" },
    {
     "title": "Data",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_bytes__average)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 largest containers (size)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, netdata_openio_container_bytes__average)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 accounts with most containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(netdata_openio_container_count__average) by (dimension))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Objects",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_objects__average{instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 largest containers (object count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, netdata_openio_container_objects__average)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 containers with biggest growth (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(rate(netdata_openio_container_bytes__average[5m]) / 300) by (dimension))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{dimension}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Containers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_count__average)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "content": "# Bandwidth" },
    {
     "title": "Bandwidth",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "format": "KBs",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\"))\n-sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"sent\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\"))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bandwidth Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_servicetype",
       "expr": "sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2)\n-sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"sent\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}}",
       "measurement": "openio_log_bandwidth",
       "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"openio_log_bandwidth\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /bytes_sent|sent/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "bytes_sent" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 }, "content": "# Requests" },
    {
     "title": "Response time",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_netdata_response_time_ms_request_average{dimension=\"average\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "expr": "sum(label_replace(netdata_web_log_response_time_milliseconds_average{family=\"timings\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_time",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_log_response_time\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\", \"namespace\", \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "expr": "sum(label_replace(netdata_web_log_response_codes_requests_persec_average{family=\"responses\", dimension=~\"4xx|5xx\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_codes",
       "query": "SELECT sum(\"value\")/($__interval_ms / 10000) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND (\"type\" = '5xx'  OR \"type\" = '4xx') AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Responses Codes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "expr": "sum(label_replace(netdata_web_log_response_codes_requests_persec_average{family=\"responses\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (dimension, chart2)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_codes",
       "query": "SELECT sum(value) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Request Method",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "expr": "sum(label_replace(netdata_web_log_http_method_requests_persec_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servicetype" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_http_method",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_log_http_method\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 }, "content": "# Redis" },
    {
     "title": "Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_keys_keys_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).keys\")) by (chart2)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_operations_operations_persec_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).operations\")) by (chart2)\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{chart2}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hit rate",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_redis_hit_rate_percent_average{instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 }, "content": "# Events" },
    {
     "title": "Event queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_tube: $tag_type",
       "expr": "sum(netdata_beanstalk_jobs_jobs_average{instance=~\"[[host]]\"}) by (family, dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "tube" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ dimension }} {{ family }}",
       "measurement": "openio_beanstalkd_tubes",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /^current.*/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"tube\", \"type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=~", "value": "/^current.*/" }
       ]
      },
      {
       "expr": "sum(netdata_beanstalk_current_jobs_jobs_average{chart=\"beanstalk_OPENIO_beanstalkd_1.current_jobs\",instance=~\"[[host]]\"}) by (dimension)",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Events Processing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: $tag_host: processed",
       "expr": "sum(netdata_beanstalk_jobs_rate_jobs_persec_average{chart=\"beanstalk_OPENIO_beanstalkd_1.jobs_rate\",family=\"server statistics\",dimension=\"total\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "tube" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "events",
       "measurement": "openio_beanstalkd_tubes",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" = 'total_jobs' AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"type\", \"tube\", \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "total_jobs" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 }, "content": "# Zookeeper" },
    {
     "title": "Datasize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: approximate_data_size",
       "expr": "sum(netdata_openio_zk_approximate_data_size__average{chart=\"openio.zk_approximate_data_size\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "data_size",
       "measurement": "openio_zookeeper_zk_approximate_data_size",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_approximate_data_size\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Pending Syncs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: pending_syncs",
       "expr": "sum(netdata_openio_zk_pending_syncs__average{instance=~\"[[host]]\"}) by (dimension)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openio_zookeeper_zk_pending_syncs",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_pending_syncs\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: avg_latency",
       "expr": "avg(netdata_openio_zk_max_latency__average{chart=\"openio.zk_max_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "openio_zookeeper_zk_avg_latency",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_namespace: max_latency",
       "expr": "avg(netdata_openio_zk_avg_latency__average{chart=\"openio.zk_avg_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "average",
       "measurement": "openio_zookeeper_zk_max_latency",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_namespace: requests",
       "expr": "avg(netdata_openio_zk_outstanding_requests__average{instance=~\"[[host]]\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "namespace" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "outstanding_requests",
       "measurement": "openio_zookeeper_zk_outstanding_requests",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_outstanding_requests\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server operations",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "alias": "$tag_host - $tag_status: $tag_title",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "title" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "events2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}