{
 "title": "OpenIO Services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Score",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggr:netdata_openio_score:avg_per_service",
     "legendFormat": "{{dim2}}"
    }
   ]
  },
  {
   "title": "Score distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_kilobytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 largest accounts (size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, netdata_openio_account_kilobytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 accounts with most containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(netdata_openio_container_count__average) by (dimension))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_objects__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 largest accounts (objects)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, netdata_openio_account_objects__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_container_count__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "S3 Roundtrip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "S3 Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(netdata_roundtrip_response_time_ms_average, \"request\", \"$1\", \"dimension\", \".*_(.*)\")) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "S3 Response code distribution",
   "type": "graph",
   "description": "Irregularities in response codes may indicate service outage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(netdata_roundtrip_response_code_ops_average, \"code\", \"$1\", \"dimension\", \"response_code_.*_(.*)\")) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Time to first byte",
   "type": "graph",
   "description": "The time it takes to successfully PUT/GET exacty 1 byte of data. Used to measure system responsiveness.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(netdata_roundtrip_ttfb_ms_average, \"request\", \"$1\", \"dimension\", \".*_(.*)\")) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "Meta2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Meta2 Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_response_codes:sum{chart2=~\".*.meta2\",dimension=~\"5xx\", instance=~\"[[host]]\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Meta2 Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_mem_MB_average{instance=~\"[[host]]\", dimension=\"openio.meta2\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Meta2 cache bases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_openio_meta2_cache_bases_cold__average{instance=~\"[[host]]\"})",
     "legendFormat": "cold"
    },
    {
     "expr": "sum(netdata_openio_meta2_cache_bases_max__average{instance=~\"[[host]]\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Meta2 elections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_openio_meta2_elections_total__average{instance=~\"[[host]]\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(netdata_openio_meta2_elections_failed__average{instance=~\"[[host]]\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(netdata_openio_meta2_elections_none__average{instance=~\"[[host]]\"})",
     "legendFormat": "none"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Gateway bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"received\", type=\"oioswift\"}) - sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\", dimension=\"sent\", type=\"oioswift\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-service bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype",
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{instance=~\"[[host]]\"}) by (type, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} {{dimension}}",
     "measurement": "openio_log_bandwidth",
     "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"openio_log_bandwidth\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /bytes_sent|sent/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bytes_sent" }
     ]
    }
   ]
  },
  {
   "title": "Average Gateway response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 73 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aggr:netdata_web_log_response_time_ms:sum{dimension=\"avg\", type=\"oioswift\", instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "avg(aggr:netdata_web_log_response_time_ms:sum{dimension=\"avg\", instance=~\"[[host]]\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "openio_log_response_time",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_log_response_time\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\", \"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_response_codes:sum{dimension=~\"4xx|5xx\", instance=~\"[[host]]\"}) by (dimension, type)",
     "legendFormat": "{{type}} {{dimension}}"
    }
   ]
  },
  {
   "title": "Max Gateway response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 80 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(aggr:netdata_web_log_response_time_ms:sum{dimension=\"max\", type=\"oioswift\", instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Responses Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 80 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "sum(aggr:netdata_web_log_response_codes:sum{instance=~\"[[host]]\"}) by (dimension, type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} {{dimension}}",
     "measurement": "openio_log_response_codes",
     "query": "SELECT sum(value) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 80 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_servicetype: $tag_type",
     "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"[[host]]\"}) by (type, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicetype" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} {{dimension}}",
     "measurement": "openio_log_http_method",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_log_http_method\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Keys",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(netdata_redis_keys__count_average{instance=~\"[[host]]\"})"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(netdata_redis_keys__count_average, 'cluster', '$1', 'family', '.*:(\\\\d+)')) by (cluster)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cluster {{cluster}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_redis_ops_ops_average) by (family)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{family}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 96 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(netdata_redis_cache_ops_average{dimension=\"hits\"}) / sum(netdata_redis_cache_ops_average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 96 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_redis_memory_bytes_average{dimension=\"total\", instance=~\"[[host]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 96 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_redis_net_bytes_average{instance=~\"[[host]]\"}) by (family)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Event queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_tube: $tag_type",
     "expr": "sum(netdata_beanstalk_jobs_jobs_average{instance=~\"[[host]]\"}) by (family, dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "tube" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ dimension }} {{ family }}",
     "measurement": "openio_beanstalkd_tubes",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /^current.*/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"tube\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^current.*/" }
     ]
    }
   ]
  },
  {
   "title": "Events Processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: $tag_host: processed",
     "expr": "sum(netdata_beanstalk_jobs_rate_jobs_persec_average{dimension=\"total\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "tube" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "events",
     "measurement": "openio_beanstalkd_tubes",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" = 'total_jobs' AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"type\", \"tube\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "total_jobs" }
     ]
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Datasize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: approximate_data_size",
     "expr": "sum(netdata_zk_data_bytes_average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "data_size",
     "measurement": "openio_zookeeper_zk_approximate_data_size",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_approximate_data_size\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader Pending Syncs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: pending_syncs",
     "expr": "sum(netdata_zk_syncs_syncs_average{instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openio_zookeeper_zk_pending_syncs",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_pending_syncs\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: avg_latency",
     "expr": "avg(netdata_zk_latency_microseconds_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "openio_zookeeper_zk_avg_latency",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_namespace: requests",
     "expr": "avg(netdata_zk_requests_requests_average{instance=~\"[[host]]\", dimension=\"outstanding\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "namespace" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "outstanding requests",
     "measurement": "openio_zookeeper_zk_outstanding_requests",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_outstanding_requests\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}