{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Failed checks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",dimension=\"user\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"value\") * -1 + 100 FROM \"[[DS]]\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"mode\" = 'idle' AND \"cpu\" = 'system' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "system" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(netdata_system_ram_MiB_average{dimension=\"used\"}) / sum(netdata_system_ram_MiB_average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ram\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GiB_average{dimension=\"used\"}) / sum(netdata_disk_space_GiB_average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aggr:netdata_openio_score:avg_per_service)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(label_replace(netdata_command__average{dimension=~\".*version.*\"}, \"output\", \"$1\", \"chart\", \".*version_(.*)[.].*\")) by (output, dimension)"
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 13, "w": 4, "x": 0, "y": 3 } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 5, "y": 4 }, "content": "### Storage" },
  {
   "title": "Used storage capacity",
   "type": "singlestat",
   "description": "Total storage used by the application. Does include replication / EC overhead.",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(label_replace(netdata_openio_byte_used__average, 'dim', '$1', 'dimension', '.*[.].*[.]([0-9]*)')) by (instance, dim))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Total storage capacity",
   "type": "singlestat",
   "description": "Total storage usable by the applications. Doesn't take into account replication / EC overhead",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(label_replace(netdata_openio_byte_avail__average, 'dim', '$1', 'dimension', '.*[.].*[.]([0-9]*)')) by (instance, dim)) + sum(avg(label_replace(netdata_openio_byte_used__average, 'dim', '$1', 'dimension', '.*[.].*[.]([0-9]*)')) by (instance, dim))"
    }
   ]
  },
  {
   "title": "Stored data",
   "type": "singlestat",
   "description": "Total amount of actual data stored in OpenIO.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_kilobytes__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects (OpenIO)",
   "type": "singlestat",
   "description": "Total number of objects in storage. Objects uploaded using MPU (Multipart Upload) may result in multiple objects created in OpenIO.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_openio_account_objects__average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 5, "y": 10 }, "content": "### Usage" },
  {
   "title": "Bandwidth (System)",
   "type": "singlestat",
   "description": "Total bandwidth as seen by the system.",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 12 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{dimension=\"received\"}) - sum(netdata_net_net_kilobits_persec_average{dimension=\"sent\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (Gateway)",
   "type": "singlestat",
   "description": "Total bandwidth as seen by the S3/Swift gateway",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 12 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aggr:netdata_web_log_bandwidth:sum{dimension=\"received\", type=\"oioswift\"}) - sum(aggr:netdata_web_log_bandwidth:sum{dimension=\"sent\", type=\"oioswift\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Response time",
   "type": "singlestat",
   "description": "Average response time of the S3 / Swift gateway",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aggr:netdata_web_log_response_time_ms:sum{dimension=\"avg\", type=\"oioswift\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server errors (1h)",
   "type": "singlestat",
   "description": "Total number of server (5xx) errors during the past hour",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(aggr:netdata_web_log_response_codes:sum{dimension=\"5xx\"}[1h]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S3 TTFB (GET)",
   "type": "singlestat",
   "description": "Time to first byte of S3 GET requests",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_roundtrip_ttfb_ms_average{dimension=\"ttfb_get\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  },
  {
   "title": "S3 TTFB (PUT)",
   "type": "singlestat",
   "description": "Time to first byte of S3 PUT requests",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_roundtrip_ttfb_ms_average{dimension=\"ttfb_put\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  },
  {
   "title": "S3 Roundtrip response time",
   "type": "singlestat",
   "description": "Average S3 roundtrip response time",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netdata_roundtrip_response_time_ms_average)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  },
  {
   "title": "S3 Roundtrip errors",
   "type": "singlestat",
   "description": "Number of 5xx errors during S3 roundtrip",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_roundtrip_response_code_ops_average{dimension=~\".*5xx\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "received" }
     ]
    }
   ]
  }
 ]
}