{
 "title": "Storage",
 "description": "Storage device information",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Percent used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"}) / (sum(netdata_disk_space_GB_average{instance=~\"[[host]]\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Capacity over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Capacity total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"}) + sum(netdata_disk_space_GB_average{dimension=\"avail\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_space",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Fill rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "1024 * 1024 * 1024 * sum(deriv(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"}[10m])) by (dimension)"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_operation",
     "expr": "sum(netdata_disk_ops_operations_persec_average{dimension=\"reads\", instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "operation" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "read",
     "measurement": "disk_ops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "-sum(netdata_disk_ops_operations_persec_average{dimension=\"writes\", instance=~\"[[host]]\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "maximum",
     "expr": "avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "maximum",
     "measurement": "disk_util",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_util\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "quantile(0.95, avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"}))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_operation",
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{instance=~\"[[host]]\", dimension=\"reads\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "operation" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "read",
     "measurement": "io",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"io\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"operation\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "-sum(netdata_disk_io_kilobytes_persec_average{instance=~\"[[host]]\", dimension=\"writes\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk Files Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_disk_inodes_Inodes_average{instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "disk_inodes",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_inodes\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "maximum",
     "expr": "quantile(0.95, avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "95th percentile",
     "measurement": "disk_backlog",
     "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_backlog\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"})",
     "legendFormat": "maximum"
    }
   ]
  }
 ]
}