{
 "title": "System",
 "description": "Global system information",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(netdata_system_cpu_percentage_average, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_mode",
     "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"cpu\" WHERE (\"cpu\" = 'system') AND $timeFilter GROUP BY time([[ds_int]]), \"mode\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "system" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"[[host]]\"}) by (dimension)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ram",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_avg",
     "expr": "avg(netdata_system_load_load_average{chart=\"system.load\",family=\"load\",instance=~\"[[host]]\"}) by (dimension)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "avg" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dimension }}",
     "measurement": "load",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"load\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"avg\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "context_switches",
     "expr": "sum(netdata_system_ctxt_context_switches_persec_average{chart=\"system.ctxt\",family=\"processes\",dimension=\"switches\",instance=~\"[[host]]\"})\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "context switches",
     "measurement": "ctxt_switches",
     "query": "SELECT sum(\"value\")  FROM \"[[DS]]\".\"ctxt_switches\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "expr": "sum(netdata_system_processes_processes_average{chart=\"system.processes\",family=\"processes\",dimension=\"running\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "running",
     "measurement": "processes",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"processes\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commited Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "commited_memory",
     "expr": "sum(netdata_mem_committed_MB_average{chart=\"mem.committed\",family=\"system\",dimension=\"Committed_AS\",instance=~\"[[host]]\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed memory",
     "measurement": "mem_committed",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"mem_committed\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}